package com.academictaskmanager.model;

import jakarta.persistence.*;

/**
 * Holds per-account customization preferences (theme color, which optional
 * widgets are enabled such as weather/sports) plus Canvas LMS connection
 * details. Each user account has exactly one settings row.
 */
@Entity
@Table(name = "user_settings")
public class UserSettings {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The account these settings belong to; one-to-one. */
    @OneToOne(optional = false)
    @JoinColumn(name = "owner_id", unique = true)
    private User owner;

    private String displayName = "Student";

    /** Primary accent color for the dashboard theme, e.g. "#4f46e5". */
    private String themeColor = "#4f46e5";

    private String themeMode = "light"; // light | dark

    // --- Optional dashboard widgets ---
    private boolean weatherWidgetEnabled = false;
    private String weatherLocation;

    private boolean sportsWidgetEnabled = false;
    private String sportsTeam;

    private boolean todoWidgetEnabled = true;
    private boolean calendarWidgetEnabled = true;

    // --- Canvas LMS integration ---
    /** Base URL of the institution's Canvas instance, e.g. https://school.instructure.com */
    private String canvasBaseUrl;

    /** Canvas API access token (personal access token generated by the student). */
    private String canvasApiToken;

    private boolean canvasSyncEnabled = false;

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public User getOwner() { return owner; }
    public void setOwner(User owner) { this.owner = owner; }

    public String getDisplayName() { return displayName; }
    public void setDisplayName(String displayName) { this.displayName = displayName; }

    public String getThemeColor() { return themeColor; }
    public void setThemeColor(String themeColor) { this.themeColor = themeColor; }

    public String getThemeMode() { return themeMode; }
    public void setThemeMode(String themeMode) { this.themeMode = themeMode; }

    public boolean isWeatherWidgetEnabled() { return weatherWidgetEnabled; }
    public void setWeatherWidgetEnabled(boolean weatherWidgetEnabled) { this.weatherWidgetEnabled = weatherWidgetEnabled; }

    public String getWeatherLocation() { return weatherLocation; }
    public void setWeatherLocation(String weatherLocation) { this.weatherLocation = weatherLocation; }

    public boolean isSportsWidgetEnabled() { return sportsWidgetEnabled; }
    public void setSportsWidgetEnabled(boolean sportsWidgetEnabled) { this.sportsWidgetEnabled = sportsWidgetEnabled; }

    public String getSportsTeam() { return sportsTeam; }
    public void setSportsTeam(String sportsTeam) { this.sportsTeam = sportsTeam; }

    public boolean isTodoWidgetEnabled() { return todoWidgetEnabled; }
    public void setTodoWidgetEnabled(boolean todoWidgetEnabled) { this.todoWidgetEnabled = todoWidgetEnabled; }

    public boolean isCalendarWidgetEnabled() { return calendarWidgetEnabled; }
    public void setCalendarWidgetEnabled(boolean calendarWidgetEnabled) { this.calendarWidgetEnabled = calendarWidgetEnabled; }

    public String getCanvasBaseUrl() { return canvasBaseUrl; }
    public void setCanvasBaseUrl(String canvasBaseUrl) { this.canvasBaseUrl = canvasBaseUrl; }

    public String getCanvasApiToken() { return canvasApiToken; }
    public void setCanvasApiToken(String canvasApiToken) { this.canvasApiToken = canvasApiToken; }

    public boolean isCanvasSyncEnabled() { return canvasSyncEnabled; }
    public void setCanvasSyncEnabled(boolean canvasSyncEnabled) { this.canvasSyncEnabled = canvasSyncEnabled; }
}
