package com.academictaskmanager.service;

import com.academictaskmanager.dto.CanvasAssignmentDto;
import com.academictaskmanager.dto.CanvasCourseDto;
import com.academictaskmanager.model.AcademicTask;
import com.academictaskmanager.model.Course;
import com.academictaskmanager.model.TaskStatus;
import com.academictaskmanager.model.TaskType;
import com.academictaskmanager.model.UserSettings;
import com.academictaskmanager.repository.AcademicTaskRepository;
import com.academictaskmanager.repository.CourseRepository;
import org.springframework.http.HttpHeaders;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;

/**
 * Syncs courses and assignments/quizzes from a student's Canvas LMS account
 * using their institution's Canvas base URL and a personal access token
 * (generated by the student under Canvas &gt; Account &gt; Settings &gt; New Access Token).
 *
 * Canvas REST API docs: https://canvas.instructure.com/doc/api/
 */
@Service
public class CanvasSyncService {

    private final RestClient restClient;
    private final CourseRepository courseRepository;
    private final AcademicTaskRepository taskRepository;

    public CanvasSyncService(RestClient restClient, CourseRepository courseRepository,
                              AcademicTaskRepository taskRepository) {
        this.restClient = restClient;
        this.courseRepository = courseRepository;
        this.taskRepository = taskRepository;
    }

    /**
     * Pulls active courses and their assignments from Canvas and upserts them
     * locally. Returns the number of tasks created or updated.
     */
    public int sync(UserSettings settings) {
        if (settings.getCanvasBaseUrl() == null || settings.getCanvasApiToken() == null) {
            throw new IllegalStateException("Canvas base URL and API token must be configured before syncing.");
        }
        String baseUrl = stripTrailingSlash(settings.getCanvasBaseUrl());
        int upserted = 0;

        List<CanvasCourseDto> canvasCourses = restClient.get()
                .uri(baseUrl + "/api/v1/courses?enrollment_state=active&per_page=100")
                .headers(h -> h.setBearerAuth(settings.getCanvasApiToken()))
                .retrieve()
                .body(new org.springframework.core.ParameterizedTypeReference<List<CanvasCourseDto>>() { });

        if (canvasCourses == null) {
            return 0;
        }

        for (CanvasCourseDto canvasCourse : canvasCourses) {
            Course course = courseRepository.findByCanvasCourseId(canvasCourse.getId())
                    .orElseGet(Course::new);
            course.setCanvasCourseId(canvasCourse.getId());
            course.setName(canvasCourse.getName());
            course.setCode(canvasCourse.getCourseCode());
            course = courseRepository.save(course);

            List<CanvasAssignmentDto> assignments = restClient.get()
                    .uri(baseUrl + "/api/v1/courses/" + canvasCourse.getId() + "/assignments?per_page=100")
                    .headers(h -> h.setBearerAuth(settings.getCanvasApiToken()))
                    .retrieve()
                    .body(new org.springframework.core.ParameterizedTypeReference<List<CanvasAssignmentDto>>() { });

            if (assignments == null) {
                continue;
            }

            for (CanvasAssignmentDto assignment : assignments) {
                AcademicTask task = taskRepository.findByCanvasAssignmentId(assignment.getId())
                        .orElseGet(AcademicTask::new);
                task.setCanvasAssignmentId(assignment.getId());
                task.setTitle(assignment.getName());
                task.setDescription(stripHtml(assignment.getDescription()));
                task.setType(assignment.isQuizAssignment() ? TaskType.QUIZ : TaskType.ASSIGNMENT);
                task.setCourse(course);
                if (assignment.getDueAt() != null) {
                    task.setDueDate(LocalDateTime.ofInstant(Instant.parse(assignment.getDueAt()), ZoneId.systemDefault()));
                }
                if (task.getStatus() == null) {
                    task.setStatus(TaskStatus.PENDING);
                }
                taskRepository.save(task);
                upserted++;
            }
        }
        return upserted;
    }

    private String stripTrailingSlash(String url) {
        return url.endsWith("/") ? url.substring(0, url.length() - 1) : url;
    }

    private String stripHtml(String html) {
        if (html == null) return null;
        String text = html.replaceAll("<[^>]*>", " ").replaceAll("\\s+", " ").trim();
        return text.isEmpty() ? null : text;
    }
}
