package com.academictaskmanager.service;

import com.academictaskmanager.dto.RecurrenceRequest;
import com.academictaskmanager.model.Event;
import com.academictaskmanager.model.User;
import com.academictaskmanager.repository.EventRepository;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Service
public class EventService {

    private final EventRepository eventRepository;

    public EventService(EventRepository eventRepository) {
        this.eventRepository = eventRepository;
    }

    /** Events starting within the given window, ordered soonest first — powers the calendar view. */
    public List<Event> findUpcoming(User owner, LocalDateTime start, LocalDateTime end) {
        return eventRepository.findByOwnerAndStartDateTimeBetweenOrderByStartDateTimeAsc(owner, start, end);
    }

    public List<Event> findAll(User owner) {
        return eventRepository.findByOwnerOrderByStartDateTimeAsc(owner);
    }

    public Event findById(Long id, User owner) {
        return eventRepository.findByIdAndOwner(id, owner).orElseThrow(() ->
                new IllegalArgumentException("Event not found: " + id));
    }

    public Event save(Event event, User owner) {
        event.setOwner(owner);
        return eventRepository.save(event);
    }

    public void delete(Long id, User owner) {
        Event event = findById(id, owner);
        eventRepository.delete(event);
    }

    /**
     * Materializes a recurring series: one independent {@link Event} row per occurrence date
     * generated by {@code recurrence}, all sharing a fresh series id and the same human-readable
     * recurrence summary. The seed's own start/end time supplies the time-of-day (and span
     * duration, if an end time is set) and, for WEEKLY, the default weekday when none is given.
     */
    public List<Event> createRecurringSeries(Event seed, RecurrenceRequest recurrence, User owner) {
        List<LocalDateTime> occurrences = RecurrenceExpander.expand(seed.getStartDateTime(), recurrence);
        Duration span = seed.getEndDateTime() != null ? Duration.between(seed.getStartDateTime(), seed.getEndDateTime()) : null;
        String seriesId = UUID.randomUUID().toString();
        String summary = RecurrenceExpander.summarize(recurrence);
        List<Event> saved = new ArrayList<>();
        for (LocalDateTime occurrence : occurrences) {
            Event event = new Event();
            event.setTitle(seed.getTitle());
            event.setDescription(seed.getDescription());
            event.setLocation(seed.getLocation());
            event.setCourse(seed.getCourse());
            event.setStartDateTime(occurrence);
            event.setEndDateTime(span != null ? occurrence.plus(span) : null);
            event.setSeriesId(seriesId);
            event.setRecurrenceSummary(summary);
            event.setOwner(owner);
            saved.add(eventRepository.save(event));
        }
        return saved;
    }

    /** Deletes every occurrence belonging to the given series that this owner has access to. */
    public void deleteSeries(String seriesId, User owner) {
        eventRepository.findBySeriesIdAndOwner(seriesId, owner).forEach(eventRepository::delete);
    }
}

