package com.academictaskmanager.service;

import com.academictaskmanager.model.AcademicTask;
import com.academictaskmanager.model.TaskStatus;
import com.academictaskmanager.model.User;
import com.academictaskmanager.dto.RecurrenceRequest;
import com.academictaskmanager.repository.AcademicTaskRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.List;

@Service
public class TaskService {

    private final AcademicTaskRepository taskRepository;

    public TaskService(AcademicTaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    public List<AcademicTask> findAll(User owner) {
        return taskRepository.findByOwnerOrderByDueDateAsc(owner);
    }

    public AcademicTask findById(Long id, User owner) {
        return taskRepository.findByIdAndOwner(id, owner).orElseThrow(() ->
                new IllegalArgumentException("Task not found: " + id));
    }

    public AcademicTask save(AcademicTask task, User owner) {
        task.setOwner(owner);
        return taskRepository.save(task);
    }

    public void delete(Long id, User owner) {
        AcademicTask task = findById(id, owner);
        taskRepository.delete(task);
    }

    public AcademicTask markComplete(Long id, User owner) {
        AcademicTask task = findById(id, owner);
        task.setStatus(TaskStatus.COMPLETED);
        return taskRepository.save(task);
    }

    /** Tasks due within the given window, ordered soonest first — powers the calendar view. */
    public List<AcademicTask> findUpcoming(User owner, LocalDateTime start, LocalDateTime end) {
        return taskRepository.findByOwnerAndDueDateBetweenOrderByDueDateAsc(owner, start, end);
    }

    /** Active (non-completed) to-dos sorted by priority then due date — powers the to-do widget. */
    public List<AcademicTask> findActiveTodos(User owner) {
        return taskRepository.findByOwnerAndStatusNotOrderByDueDateAsc(owner, TaskStatus.COMPLETED).stream()
                .sorted(Comparator.comparingInt(AcademicTask::getPriority).reversed()
                        .thenComparing(AcademicTask::getDueDate, Comparator.nullsLast(Comparator.naturalOrder())))
                .toList();
    }

    /**
     * Materializes a recurring series: one independent {@link AcademicTask} row per occurrence
     * date generated by {@code recurrence}, all sharing a fresh series id and the same
     * human-readable recurrence summary. The seed's own due date supplies the time-of-day and
     * (for WEEKLY) the default weekday when none is specified.
     */
    public List<AcademicTask> createRecurringSeries(AcademicTask seed, RecurrenceRequest recurrence, User owner) {
        List<LocalDateTime> occurrences = RecurrenceExpander.expand(seed.getDueDate(), recurrence);
        String seriesId = java.util.UUID.randomUUID().toString();
        String summary = RecurrenceExpander.summarize(recurrence);
        List<AcademicTask> saved = new java.util.ArrayList<>();
        for (LocalDateTime occurrence : occurrences) {
            AcademicTask task = new AcademicTask();
            task.setTitle(seed.getTitle());
            task.setDescription(seed.getDescription());
            task.setType(seed.getType());
            task.setPriority(seed.getPriority());
            task.setCourse(seed.getCourse());
            task.setDueDate(occurrence);
            task.setSeriesId(seriesId);
            task.setRecurrenceSummary(summary);
            task.setOwner(owner);
            saved.add(taskRepository.save(task));
        }
        return saved;
    }

    /** Deletes every occurrence belonging to the given series that this owner has access to. */
    public void deleteSeries(String seriesId, User owner) {
        taskRepository.findBySeriesIdAndOwner(seriesId, owner).forEach(taskRepository::delete);
    }
}
